meta:
  schema-version: 0.1.0
  created-on: "2024-02-15T11:42:45Z"
  cli-version: 0.2.0
projects:
  ? 2lambda123-sql-server-samples-samples-demos-azure-sql-edge-demos-wind-turbine-demo-webappsrc-sqldbedgedemoweb-sqldbedgedemo.web-clientapp-package-lock.json
  : targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "5"
    overrides:
      semver:
        6.3.0:
          use: 6.3.0-sp1
        7.3.8:
          use: 7.3.8-sp1
        5.7.1:
          use: 5.7.1-sp1
      nth-check:
        1.0.2:
          use: 1.0.2-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      tough-cookie:
        4.1.2:
          use: 4.1.2-sp1
        2.5.0:
          use: 2.5.0-sp1
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      ip:
        2.0.0:
          use: 2.0.0-sp1
      postcss:
        7.0.39:
          use: 7.0.39-sp1
